Style/Documentation:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/MethodDefParentheses:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Blocks:
  Enabled: false
Metrics/MethodLength:
  Max: 18
Metrics/CyclomaticComplexity:
  Max: 7
Style/FileName:
  Enabled: false
Style/WordArray:
  MinSize: 2
