source "https://rubygems.org"

gem "slop", "~> 3.6"
gem "manowar", "0.0.1"
gem "rspec", "~> 3.1", require: false, group: :development
gem "rubocop", "~> 0.28", require: false, group: :development
gem "rubycritic", "~> 2.8", require: false, group: :development
gem "simplecov", "~> 0.9", require: false, group: :development
gem "simplecov-lcov", "~> 0.4", require: false, group: :development
