ruby:
  enabled: true
  config_file: ruby/.rubocop.yml

coffee_script:
    enabled: true
    config_file: coffeelint.json

java_script:
    enabled: true
    config_file: .jshintrc
    ignore_file: .jshintignore
