vile:
  ignore:
    - appveyor.yml
    - bin
    - circle.yml
    - CODE_OF_CONDUCT.md
    - coffeelint.json
    - coverage
    - .editorconfig
    - .git
    - .gitattributes
    - .gitignore
    - LICENSE
    - node_modules
    - .nyc_output
    - package-lock.json
    - README.md
    - src/@types
    - tags
    - test/fixtures/**
    - test/mocha.opts
    - tsconfig.json
    - tslint.json
    - tmp
    - .travis.yml
    - retire-report.json
    - .vile.yml

depcheck:
  config:
    ignore_dev_deps: true
    ignore_deps:
      - "@types/**"
    ignore_dirs:
      - src
      - node_modules
      - tmp

synt:
  ignore:
    - lib

eclint:
  ignore:
    - lib

retire:
  config:
    package: true
    node: true
    js: false
    ignore:
      - lib

comment:
  ignore:
    - lib

escomplex:
  allow:
    - lib
  ignore:
    - src

coverage:
  config:
    path: coverage/lcov.info

language:
  ignore:
    - lib

coffeelint:
  config: coffeelint.json
