version: '2.1'

orbs:
  node: circleci/node@5.1.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: '20.10'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Versions
          command: sh bin/list-env-versions
      - run:
          name: Install
          command: npm i
      - run:
          name: Test
          command: npm run test-ci-build
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
